M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date Fri 09 Sep 2022 07:22:26 PM IST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-09T19:22:26+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.450
%
G90
G05
T1
X175.93Y-111.38
T2
X91.669Y-111.608
X186.944Y-88.9
T3
X112.4Y-111.38
X167.6Y-127.38
T0
M30
